#!/bin/bash -e
#
# Create a new file and the required path
# author: @planetsLightningArrester
# shellcheck disable=SC2059

test -z "$1" && printf "\n[${TC_LIGHTRED}ERROR${TC_NOCOLOR}] Missing argument\n\n" && return-error

mkdir -p "$(dirname "$1")"
touch "$1"

# EOF
