#!/bin/bash -e
#
# Trim leading and trailing spaces (for scripts)
# author: @planetsLightningArrester

var="$*"
var="${var#"${var%%[![:space:]]*}"}" # remove leading whitespace characters
var="${var%"${var##*[![:space:]]}"}" # remove trailing whitespace characters
echo -n "$var"

# EOF

