#!/bin/bash -e
#
# Extracts any archive(s)
# author: @planetsLightningArrester
# shellcheck disable=SC2059

for archive in "$@"; do
	if [ -f "$archive" ]; then
		case "$archive" in
		*.tar.bz2) tar xjf "$archive" ;;
		*.tar.gz) tar xzf "$archive" ;;
		*.bz2) bunzip2 "$archive" ;;
		*.rar) rar x "$archive" ;;
		*.gz) gunzip "$archive" ;;
		*.tar) tar xf "$archive" ;;
		*.tbz2) tar xjf "$archive" ;;
		*.tgz) tar xzf "$archive" ;;
		*.zip) unzip "$archive" ;;
		*.Z) uncompress "$archive" ;;
		*.7z) 7z x "$archive" ;;
		*) printf "\n[${TC_LIGHTRED}ERROR${TC_NOCOLOR}] Don't know how to extract '%s'..." "$archive" ;;
		esac
	else
		printf "\n[${TC_LIGHTRED}ERROR${TC_NOCOLOR}] No such file '$archive' or not a valid file.\n\n"
	fi
done

# EOF

