-- bootstrap lazy.nvim, LazyVim and your plugins
require("config.lazy")
require("config.common")
require("config.treesitter")
require("config.telescope")
require("config.notify")
require("config.colorscheme")
require("config.python")
require("config.shfmt")
require("config.mini_indentscope")
require("config.dap.dap")
