#!/bin/bash
# shellcheck disable=SC2006,SC2016

#########################################################################################
# Q: What's this file?
#   A: This file holds all useful envs in cross-shell format
# Q: If this is cross-shell, why does it have a shebang?
#   A: Just used to enable the linter provider
# Q: How is this cross-shell?
#   A: Basically, alias is "set-alias", and (un)setenv is a ./functions in Bash. Conditional
#      statements are handled by the command `test`
#      ! So, do not use "alias"! Use "set-alias"!
#########################################################################################

# ? Disable the bell
# Ignore case on auto-completion
# Note: bind used instead of sticking these in .inputrc
# Show auto-completion list automatically, without double tab
test "$SHELL" = '/bin/bash' && iatest=`expr index "$-" i` && [[ $iatest -gt 0 ]] && bind "set bell-style visible" && [[ $iatest -gt 0 ]] && bind "set completion-ignore-case on" && [[ $iatest -gt 0 ]] && bind "set show-all-if-ambiguous On" && shopt -s checkwinsize && shopt -s histappend
test "$SHELL" = '/bin/bash' && iatest=`expr index "$-" i` && [[ $iatest -gt 0 ]] && bind "set bell-style visible" && bind "set completion-ignore-case on" && bind "set show-all-if-ambiguous On"
# Check the window size after each command and, if necessary, update the values of LINES and COLUMNS
# Causes bash to append to history instead of overwriting it so if you start a new terminal, you have old session history
test "$SHELL" = '/bin/bash' && shopt -s checkwinsize && shopt -s histappend

#######################################################
# C-Shell exclusive options
#######################################################

# Ignore case on auto-completion
# Show auto-completion list automatically, without double tab
test "$SHELL" = '/bin/csh' && setenv autolist ambiguous && setenv complete enhance

#######################################################
# Common options
#######################################################

# creates new files with -rw-rw-r--
umask 002

# Expand the history size
setenv HISTFILESIZE "50000"
setenv HISTSIZE "500"

# Don't put duplicate lines in the history and do not add lines that start with a space
setenv HISTCONTROL "erasedups:ignoredups:ignorespace"

# Check the window size after each command and, if necessary, update the values of LINES and COLUMNS

# Causes bash to append to history instead of overwriting it so if you start a new terminal, you have old session history
setenv PROMPT_COMMAND 'history -a'

# Get the OS to print in prompt
setenv _distro_name "`getdistro`"
setenv DISTRO_VERSION "`getdistrover`"
setenv RED "\033[0;31m"
setenv GREEN "\033[0;32m"
setenv MAGENTA "\033[0;35m"
setenv YELLOW "\033[1;33m"
setenv NOCOLOR "\033[0m"
test "$_distro_name" = "Red Hat Enterprise Linux Workstation" && setenv DISTRO_NAME "${TC_RED}󱄛${TC_NOCOLOR}"
test "$_distro_name" = "Red Hat Enterprise Linux" && setenv DISTRO_NAME "${TC_RED}󱄛${TC_NOCOLOR}"
test "$_distro_name" = "CentOS Linux" && setenv DISTRO_NAME "${TC_MAGENTA}${TC_NOCOLOR}"
test "$_distro_name" = "SLES" && setenv DISTRO_NAME "${TC_GREEN}${TC_NOCOLOR}"
test "$_distro_name" = "Ubuntu" && setenv DISTRO_NAME "${TC_YELLOW}${TC_NOCOLOR}"
unsetenv _distro_name

# VS Code and VS Code insiders
setenv EDITOR ""
test "`command -v code`" && setenv EDITOR "code --wait"
test ! "`command -v code`" && test "`command -v code-insiders`" && set-alias code 'code-insiders' && setenv EDITOR "code-insiders --wait"
test -z "$EDITOR" && setenv EDITOR nvim

setenv VISUAL "$EDITOR"
set-alias edit '$EDITOR'

# To have colors for ls and all grep commands such as grep, egrep and zgrep
setenv CLICOLOR 1
unsetenv LS_COLORS
unsetenv GREP_OPTIONS

# Color for manpages in less makes manpages a little easier to read
# # TODO Only working for Bash
# test "$SHELL" = "/bin/bash" && setenv LESS_TERMCAP_mb $'\E[01;31m';
# test "$SHELL" = "/bin/bash" && setenv LESS_TERMCAP_md $'\E[01;31m';
# test "$SHELL" = "/bin/bash" && setenv LESS_TERMCAP_me $'\E[0m';
# test "$SHELL" = "/bin/bash" && setenv LESS_TERMCAP_se $'\E[0m';
# test "$SHELL" = "/bin/bash" && setenv LESS_TERMCAP_so $'\E[01;44;33m';
# test "$SHELL" = "/bin/bash" && setenv LESS_TERMCAP_ue $'\E[0m';
# test "$SHELL" = "/bin/bash" && setenv LESS_TERMCAP_us $'\E[01;32m';

# PATH
setenv PERL5LIB "$HOME/lib/perl5:$PERL5LIB"
setenv PATH "$HOME/.local/bin:$HOME/local/bin:$PATH"
setenv LD_LIBRARY_PATH "$HOME/.local/lib:$HOME/local/lib:$LD_LIBRARY_PATH"

# EOF

